# Generated by Django 5.0.13 on 2025-04-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="accepting_users",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="join_code",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
