# Generated by Django 5.0.13 on 2025-04-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_organization_accepting_users_organization_join_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "permissions": (
                    ("user", "Member of org"),
                    ("mod", "Moderator of org"),
                    ("admin", "Admin of org"),
                )
            },
        ),
    ]
