# Generated by Django 5.0.13 on 2025-04-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_path", models.CharField(max_length=200)),
                ("user_id", models.IntegerField()),
                ("organization_id", models.IntegerField()),
                ("status", models.BooleanField(default=False)),
                ("created", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
