# Generated by Django 5.0.14 on 2025-04-28 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crowd_app", "0001_initial"),
        ("media_app", "0002_remove_media_tag_tag_media_tag"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
