# Generated by Django 5.0.13 on 2025-04-14 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowd_app", "0002_organization_tag_remove_media_organization_id_and_more"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.organization",
            ),
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
    ]
