# Generated by Django 5.0.14 on 2025-04-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="status",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
