# Generated by Django 5.0.14 on 2025-04-28 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_app", "0001_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="tag",
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="media",
            name="tag",
            field=models.ManyToManyField(blank=True, to="media_app.tag"),
        ),
    ]
