# Generated by Django 5.0.14 on 2025-04-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_app", "0002_remove_media_tag_tag_media_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="bg_color",
            field=models.CharField(default="#F07857", max_length=7),
        ),
    ]
